In [110]:
import numpy as np

In [ ]:
# array
# 1-dimension, 2D, 3D-------nD

In [3]:
df = np.array([32,22,54,76,98])   # list array
df

array([32, 22, 54, 76, 98])

In [7]:
df[2]

54

In [11]:
print(df[-2])
print(df[1:4])

76
[22 54 76]


In [5]:
df1 = np.array((9,8,7,12,15))   # tuple array
df1

array([ 9,  8,  7, 12, 15])

In [21]:
# 2 Dimension array
ab = np.array([[12,33,14,15],[7,8,66,24]])   # 2 x 4 matrics - 2 row and 4 columns
ab

array([[12, 33, 14, 15],
       [ 7,  8, 66, 24]])

In [25]:
ab[1][2]  # row index, column index

66

In [27]:
ab[0][1]

33

In [35]:
# 3D
df2 = np.array([[[23,22,45,76],[23,29,89,90]]])
df2

array([[[23, 22, 45, 76],
        [23, 29, 89, 90]]])

In [47]:
df2[0][1][3]

90

In [49]:
# zeros
df3 = np.zeros((2,3))   # row, column
df3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
#ones
df4 = np.ones((3,4))
df4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
# full
df4 = np.full((3,4),6)
df4

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [55]:
df5 = np.full((3,3),10)
df5

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [59]:
# shape
df5.shape

(3, 3)

In [69]:
print(df5.size)  #number of elements
print(df5.itemsize)   # bytes of each value/element/item
print(df5.size*df5.itemsize)
print(df5.nbytes)   # total bytes of array

9
4
36
36


In [73]:
# dtype  - data type
print(df5.dtype)
# ndim - number of dimension
print(df5.ndim)


int32
2


In [75]:
df = np.zeros((3,4)) 
df

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
df[0][1] = 5
df

array([[0., 5., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
ab = np.array([23,22,12,7])
ab


array([23, 22, 12,  7])

In [81]:
ab[1]=10
ab

array([23, 10, 12,  7])

In [50]:
ab2 = np.zeros((3,3),dtype=int)
ab2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
ab2[0][0]= 1
ab2[1][1] = 1
ab2[2][2] = 1

In [42]:
ab2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [52]:
arr1 = np.array([54,87,78,90])
arr1

array([54, 87, 78, 90])

In [58]:
arr1 = np.append(arr1,15)
arr1

array([54, 87, 78, 90, 15])

In [64]:
# insert
arr1 = np.insert(arr1,1,50)
arr1

array([54, 50, 87, 78, 90, 15])

In [66]:
arr1

array([54, 50, 87, 78, 90, 15])

In [70]:
np.delete(arr1,4)

array([54, 50, 87, 78, 15])

In [3]:
#linspace
df = np.linspace(2,10,4)
df

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [5]:
df2 = np.linspace(10,100,10)
df2

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [11]:
# random
df3 = np.random.random(20)
df3

array([0.45452431, 0.47343175, 0.78861966, 0.16806659, 0.04780541,
       0.46582373, 0.69539047, 0.10096435, 0.51717039, 0.18493454,
       0.93411801, 0.30406881, 0.09262039, 0.90108151, 0.39970557,
       0.49487474, 0.27729425, 0.28702954, 0.66174641, 0.09331424])

In [13]:
# randint
df3 = np.random.randint(1,10,5)  # start,stop, number of elements
df3


array([7, 7, 6, 2, 3])

In [15]:
arr1 = np.array([23,22,26,87])
arr1

array([23, 22, 26, 87])

In [17]:
arr1.dtype

dtype('int32')

In [19]:
# astype
arr2 = arr1.astype("float")
arr2

array([23., 22., 26., 87.])

In [21]:
arr2.dtype

dtype('float64')

In [22]:
# choice
df4 = np.random.choice([23,22,87,98,89],size=2)
df4

# shuffle

#seed


array([98, 89])

In [24]:
# shuffle
df6 = np.array([23,22,87,78])
np.random.shuffle([23,22,87,78])
np.random.shuffle(df6)

In [36]:
df7 = np.array([34,11,13,87])

np.random.shuffle(df7)
df7

array([11, 13, 34, 87])

In [28]:
# seed
np.random.seed(64)


### sorting

In [41]:
ab = np.array([7,5,4,9,1,6])
sortedAb = np.sort(ab)
sortedAb

array([1, 4, 5, 6, 7, 9])

In [43]:
d2 = np.array([[4,3,6,8],[12,15,6,9]])
d2

array([[ 4,  3,  6,  8],
       [12, 15,  6,  9]])

In [45]:
sortdD2 = np.sort(d2)
sortdD2

array([[ 3,  4,  6,  8],
       [ 6,  9, 12, 15]])

In [47]:
sortdD2 = np.sort(d2,axis=0)   # column wise axis=0       axis=1  row wise
sortdD2  

array([[ 4,  3,  6,  8],
       [12, 15,  6,  9]])

### reverse

In [52]:
arr3 = np.array([1,2,3,4,5])
arr5 = arr3[::-1]
arr5

array([5, 4, 3, 2, 1])

## Aggregation Function

In [55]:
arr2 = np.array([[12,4,7,8],[8,9,19,6]])
arr2

array([[12,  4,  7,  8],
       [ 8,  9, 19,  6]])

In [61]:
print(np.sum(arr2))  # total sum
print(np.sum(arr2,axis=0))  # column wise
print(np.sum(arr2,axis=1))  # row wise

73
[20 13 26 14]
[31 42]


In [69]:
# mean
print(np.mean(arr2))
print(np.mean(arr2,axis=0))
print(np.mean(arr2,axis=1))

9.125
[10.   6.5 13.   7. ]
[ 7.75 10.5 ]


In [71]:
# minimum
# maximum
# std deviatin
# variance
# count

## Concatenation

In [74]:
a = np.array([[2,4],[6,9]])
b  = np.array([[4,5],[12,32]])
print(a)
print(b)

[[2 4]
 [6 9]]
[[ 4  5]
 [12 32]]


In [78]:
print(np.concatenate((a,b),axis=0))  # row wise

[[ 2  4]
 [ 6  9]
 [ 4  5]
 [12 32]]


In [80]:
print(np.concatenate((a,b),axis=1))

[[ 2  4  4  5]
 [ 6  9 12 32]]


In [84]:
# stacking funcion -- vstack , hstack
#vsertical stack
a = np.array([[2,4],[6,9]])
b  = np.array([[4,5],[12,32]])

print(np.vstack((a,b)))

[[ 2  4]
 [ 6  9]
 [ 4  5]
 [12 32]]


In [88]:
# horizontal stack
print(np.hstack((a,b)))

[[ 2  4  4  5]
 [ 6  9 12 32]]


## Matrix Multiplication

In [91]:
# dot
# mat mul
# element wise multplication

In [95]:
a = np.array([[2,4],[6,9]])
b  = np.array([[4,5],[12,32]])
print(a)
print(b)
result = np.dot(a,b)
print(result)

[[2 4]
 [6 9]]
[[ 4  5]
 [12 32]]
[[ 56 138]
 [132 318]]


In [97]:
result2 = np.matmul(a,b)  # matrix multiplication
print(result2)

[[ 56 138]
 [132 318]]


In [99]:
result3 = a*b
print(result3)

[[  8  20]
 [ 72 288]]


## Import Data

In [104]:
data = np.genfromtxt("myData.txt",delimiter=",")
data

array([12., 13., 15., 17., 22.])

In [108]:
data1 = np.genfromtxt("C:/Users/DELL/Desktop/myData.txt",delimiter=",")
data1

array([12., 13., 15., 17., 22.])

In [122]:
data2 = np.genfromtxt("data2.txt",dtype=[("name","U10"),("maths_mark",int),("phy_mark",int),("chem_mark",int)],delimiter=",",names=True,missing_values="",filling_values=0,encoding="utf-8")  # unicode transformation Format
print(data2)

[('Alan', 56, 63, 78) ('Jhon', 78,  0, 89) ('David', 45, 46, 36)]


### Boolean Masking

In [125]:
arr1 = np.array([23,6,7,19,78,5])
arr1

array([23,  6,  7, 19, 78,  5])

In [131]:
mask = arr1>10
print(mask)
print(arr1[mask])

[ True False False  True  True False]
[23 19 78]


In [133]:
arr1[arr1>10]

array([23, 19, 78])

In [135]:
arr1[arr1<10]

array([6, 7, 5])

In [139]:
# arange - array range

arr2 = np.arange(2,10)   # start,stop,step
arr2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
arr3 = np.arange(10,100,10)
arr3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [145]:
arr4 = np.arange(2,20)
arr4

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [147]:
arr4[arr4 % 2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [149]:
df = np.array([7,8,-6,32,-7])
df

array([ 7,  8, -6, 32, -7])

In [153]:
# replacing values using masking
df[df<0] = 0

In [155]:
df

array([ 7,  8,  0, 32,  0])

### Array Splitting

In [158]:
# split - splitting array equal parts
# array_split -- splittin array into unequal parts
# hsplit -- horizontal split (2D array)
# vsplit -- vertical split (2D array)
# dsplit --depth wis split (3D array)

In [162]:
# split
arr = np.array([10,20,30,55,76,87,12,8,45])
print(arr)
spliting = np.split(arr,3)
print(spliting)

[10 20 30 55 76 87 12  8 45]
[array([10, 20, 30]), array([55, 76, 87]), array([12,  8, 45])]


In [166]:
# array _split
arr1 = np.array([10,20,30,55,76,87,12,8,45,56])
parts = np.array_split(arr1,4)
print(parts)

[array([10, 20, 30]), array([55, 76, 87]), array([12,  8]), array([45, 56])]


In [168]:
arr2 = np.array([[23,89,66],[65,98,8],[12,14,15]])
arr2

array([[23, 89, 66],
       [65, 98,  8],
       [12, 14, 15]])

In [170]:
hsplit = np.hsplit(arr2,3)
hsplit

[array([[23],
        [65],
        [12]]),
 array([[89],
        [98],
        [14]]),
 array([[66],
        [ 8],
        [15]])]

In [172]:
vsplit = np.vsplit(arr2,3)
vsplit

[array([[23, 89, 66]]), array([[65, 98,  8]]), array([[12, 14, 15]])]

In [174]:
# dsplit
df2 = np.array([[[1,2,3,4],[7,6,8,9]]])
df2

array([[[1, 2, 3, 4],
        [7, 6, 8, 9]]])

In [176]:
df2.shape  # main bracket (2 bracket)-block, number of list(rows),number of elements

(1, 2, 4)

In [178]:
parts3 = np.dsplit(df2,2)
parts3

[array([[[1, 2],
         [7, 6]]]),
 array([[[3, 4],
         [8, 9]]])]

### Union

In [181]:
a = np.array([5,6,7,8])
b = np.array([7,8,9,10])
union = np.union1d(a,b)
print(union)

[ 5  6  7  8  9 10]


In [183]:
# intresection
commonValues = np.intersect1d(a,b)
commonValues

array([7, 8])

In [ ]:
EDA - EXploratory Data Analysis