## Probabilty

In [1]:
import numpy as np

In [4]:
population = np.random.randint(100,200,150)
population

array([102, 163, 194, 191, 185, 157, 172, 129, 114, 123, 193, 155, 198,
       133, 105, 186, 103, 132, 137, 108, 115, 118, 133, 192, 174, 175,
       120, 100, 141, 176, 149, 194, 173, 180, 167, 162, 103, 179, 140,
       128, 173, 153, 121, 174, 152, 196, 183, 157, 105, 127, 152, 108,
       143, 178, 177, 122, 173, 147, 128, 156, 156, 183, 152, 165, 111,
       111, 187, 101, 122, 172, 164, 129, 169, 186, 115, 139, 110, 133,
       159, 158, 169, 103, 141, 196, 123, 127, 101, 108, 192, 179, 168,
       124, 132, 135, 124, 189, 112, 158, 193, 187, 101, 169, 132, 181,
       185, 164, 106, 153, 172, 124, 158, 149, 180, 163, 154, 182, 189,
       147, 116, 105, 199, 177, 178, 147, 150, 157, 130, 160, 146, 182,
       107, 166, 115, 139, 117, 178, 141, 183, 145, 164, 160, 130, 199,
       155, 199, 183, 145, 193, 170, 197])

In [6]:
sample1 = np.random.choice(population,20)
sample1

array([127, 105, 111, 155, 100, 186, 108, 193, 194, 160, 150, 199, 172,
       170, 130, 102, 150, 174, 155, 182])

In [8]:
sample2 = np.random.choice(population,30)
sample2

array([172, 168, 156, 127, 141, 139, 132, 181, 133, 105, 110, 135, 183,
       153, 156, 123, 107, 158, 122, 130, 178, 123, 124, 199, 193, 120,
       183, 147, 105, 156])

### Quartile and InterQuartile

In [4]:
data=np.array([4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8])
data

array([4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8])

In [8]:
q1 = np.percentile(data,25)
q1

5.0

In [10]:
q3 = np.percentile(data,75)
q3

7.0

In [12]:
q4 = np.percentile(data,100)
q4

8.0

In [14]:
q4-q1

3.0

## Variance & Std Deviation

In [17]:
data=np.array([4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8])
data

array([4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8])

In [19]:
np.var(data)  # variation

1.1666666666666667

In [21]:
np.std(data) # std deviation

1.0801234497346435